package dev.rovernotes.retrieval;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.Optional;

import org.junit.jupiter.api.Test;

/**
 * The router's classification rule.
 *
 * <p>The cases that matter are the negative ones. Routing an identifier to the lexical
 * channel is worth 0.0863 nDCG@10 on the queries it is meant for; routing a question
 * there costs whatever fusion was contributing, and the eval set that measured the gain
 * cannot see that error because its identifier queries are generated by this same rule.
 */
class QueryRouterTest {

    private final QueryRouter router = new QueryRouter();

    @Test
    void routesTokensCarryingAnIdentifierMark() {
        for (String query : new String[] {
                "event_publication", "vector_cosine_ops", "hnsw.iterative_scan",
                "claude-haiku-4-5", "A10G", "ModularityTests", "Retry-After"}) {
            assertThat(router.route(query))
                    .as("query %s", query)
                    .contains(RetrievalMode.LEXICAL);
        }
    }

    @Test
    void leavesQuestionsAlone() {
        for (String query : new String[] {
                "How are ranked lists combined?",
                "Why not normalise the scores before merging them?",
                "outbox pattern",
                "what is a cross-encoder"}) {
            assertThat(router.route(query)).as("query %s", query).isEmpty();
        }
    }

    @Test
    void leavesOrdinaryWordsAlone() {
        // Both occur in exactly one corpus document, so a rule built on uniqueness alone
        // would route them. Neither is a token a reader types to find a document again.
        assertThat(router.route("configuration")).isEmpty();
        assertThat(router.route("construction")).isEmpty();
    }

    @Test
    void anInitialCapitalIsNotAnIdentifierMark() {
        // Otherwise the first word of any sentence classifies as an identifier, and a
        // one-word question routes.
        assertThat(router.route("Configuration")).isEmpty();
        assertThat(router.route("Retrieval")).isEmpty();
    }

    @Test
    void requiresASingleToken() {
        // Several tokens mean the reader is describing what they want rather than naming
        // it, and the measurement behind this rule covers single-token lookups only.
        assertThat(router.route("event_publication rows")).isEmpty();
        assertThat(router.route("what does ts_rank_cd do")).isEmpty();
    }

    @Test
    void ignoresSurroundingWhitespace() {
        assertThat(router.route("  ts_rank_cd  ")).contains(RetrievalMode.LEXICAL);
    }

    @Test
    void shortTokensDoNotRoute() {
        // Too little to be sure of, and the lexical channel has no advantage on them.
        assertThat(router.route("a-b")).isEmpty();
        assertThat(router.route("id")).isEmpty();
    }

    @Test
    void handlesAbsentAndEmptyQueries() {
        assertThat(router.route(null)).isEqualTo(Optional.empty());
        assertThat(router.route("   ")).isEmpty();
    }
}
