-- Rover Notes 2.0 — baseline schema
--
-- One Postgres serving vector search, lexical search, a bounded entity graph,
-- a job queue, and cost accounting. See `docs/ARCHITECTURE.md`
--
-- Embedding dimension 384 matches BAAI/bge-small-en-v1.5 (see docs/ARCHITECTURE.md).
-- Changing the embedding model means a new column and a backfill, not an ALTER.

create extension if not exists vector;
create extension if not exists pg_trgm;
create extension if not exists pgcrypto;

-- ============================================================ documents

create table documents (
    id            uuid primary key default gen_random_uuid(),
    owner_id      uuid        not null,
    title         text        not null,
    source_type   text        not null default 'note',   -- note | pdf | web | email | code
    source_uri    text,                                  -- s3 key, URL, or null for notes
    content       text,                                  -- extracted plain text
    content_hash  text        not null,                  -- sha256; drives re-index idempotency
    metadata      jsonb       not null default '{}'::jsonb,
    created_at    timestamptz not null default now(),
    updated_at    timestamptz not null default now(),

    constraint documents_source_type_check
        check (source_type in ('note', 'pdf', 'web', 'email', 'code', 'audio', 'image'))
);

create index documents_owner_updated_idx on documents (owner_id, updated_at desc);

-- Known-item lookup: "find the file about X" resolves here in single-digit ms
-- before any neural work happens. See docs/ARCHITECTURE.md, routing stage.
create index documents_title_trgm_idx on documents using gin (title gin_trgm_ops);

create index documents_metadata_idx on documents using gin (metadata jsonb_path_ops);

-- ============================================================ chunks

create table chunks (
    id                     uuid  primary key default gen_random_uuid(),
    document_id            uuid  not null references documents (id) on delete cascade,

    -- Denormalised from documents so owner filters push down into the same
    -- index scan as the vector search rather than forcing a join first.
    owner_id               uuid  not null,

    ordinal                int   not null,
    content                text  not null,

    -- Contextual retrieval: `content` prefixed with a chunk-situating sentence
    -- generated by a cheap model. This is what gets embedded; `content` is what
    -- gets shown to the user. Populated in Week 4.
    contextualized_content text,

    -- sha256 of `content`. Ingestion skips re-embedding when unchanged, so
    -- editing one paragraph of a 40-page document re-embeds one chunk, not 400.
    content_hash           text  not null,

    token_count            int,

    -- Character offsets into documents.content, for span-level citation grounding.
    char_start             int,
    char_end               int,

    embedding              vector(384),

    tsv tsvector generated always as (to_tsvector('english', content)) stored,

    created_at             timestamptz not null default now(),

    constraint chunks_ordinal_unique unique (document_id, ordinal)
);

-- Dense channel. m/ef_construction are starting values; ef_search is tuned at
-- query time against the eval set in Week 4, not guessed.
create index chunks_embedding_hnsw_idx
    on chunks using hnsw (embedding vector_cosine_ops)
    with (m = 16, ef_construction = 64);

-- Lexical channel. Carries known-item queries, where dense retrieval is weakest.
create index chunks_tsv_idx on chunks using gin (tsv);

create index chunks_owner_idx    on chunks (owner_id);
create index chunks_document_idx on chunks (document_id);
create index chunks_hash_idx     on chunks (content_hash);

-- ============================================================ entity graph
--
-- Relational, not a graph database: traversal is bounded at 2 hops from a
-- retrieved seed set, which is two joins. See docs/ARCHITECTURE.md.

create table entities (
    id           uuid primary key default gen_random_uuid(),
    owner_id     uuid not null,
    name         text not null,
    entity_type  text not null,          -- person | project | concept | org | ...
    canonical_id uuid references entities (id) on delete set null,  -- alias resolution
    created_at   timestamptz not null default now(),

    constraint entities_name_unique unique (owner_id, name, entity_type)
);

create index entities_owner_idx     on entities (owner_id);
create index entities_name_trgm_idx on entities using gin (name gin_trgm_ops);

create table entity_mentions (
    entity_id  uuid not null references entities (id) on delete cascade,
    chunk_id   uuid not null references chunks (id)   on delete cascade,
    confidence real not null default 1.0,

    primary key (entity_id, chunk_id)
);

create index entity_mentions_chunk_idx on entity_mentions (chunk_id);

create table entity_edges (
    src_id      uuid not null references entities (id) on delete cascade,
    dst_id      uuid not null references entities (id) on delete cascade,
    relation    text not null,
    confidence  real not null default 1.0,
    source_doc  uuid references documents (id) on delete set null,
    created_at  timestamptz not null default now(),

    primary key (src_id, dst_id, relation)
);

create index entity_edges_dst_idx on entity_edges (dst_id);

-- ============================================================ outbox
--
-- Transactional outbox + job queue. Written in the same transaction as the
-- document, so there is no dual-write problem. See docs/ARCHITECTURE.md.

create table outbox (
    id              bigserial   primary key,
    aggregate_type  text        not null,      -- document | chunk
    aggregate_id    uuid        not null,
    event_type      text        not null,      -- document.created | document.updated | ...
    payload         jsonb       not null default '{}'::jsonb,
    status          text        not null default 'pending',
    attempts        int         not null default 0,
    last_error      text,
    next_attempt_at timestamptz not null default now(),
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now(),

    constraint outbox_status_check
        check (status in ('pending', 'processing', 'done', 'failed'))
);

-- Partial index: workers only ever scan claimable rows, so the index stays
-- small regardless of how much completed history accumulates.
create index outbox_claim_idx
    on outbox (next_attempt_at, id)
    where status = 'pending';

create index outbox_status_idx on outbox (status);

-- Workers claim with:
--   select * from outbox
--    where status = 'pending' and next_attempt_at <= now()
--    order by id
--      for update skip locked
--    limit 100;

-- ============================================================ model registry
--
-- Models are rows, not an enum: adding one is a migration, not a deploy.
-- Capability flags gate the UI — a model without tool support cannot be
-- selected for agent mode.

create table models (
    id                 text primary key,          -- 'anthropic/claude-sonnet-5'
    provider           text not null,             -- anthropic | openai_compat | ollama
    model_id           text not null,             -- provider-native identifier
    display_name       text not null,
    tier               text not null,             -- budget | balanced | frontier
    cost_in_per_mtok   numeric(10, 4),
    cost_out_per_mtok  numeric(10, 4),
    context_window     int  not null,
    supports_tools     boolean not null default false,
    supports_streaming boolean not null default true,
    enabled            boolean not null default true,
    created_at         timestamptz not null default now(),

    constraint models_provider_check check (provider in ('anthropic', 'openai_compat', 'ollama')),
    constraint models_tier_check     check (tier in ('budget', 'balanced', 'frontier'))
);

-- Seed: the three Anthropic tiers. Open-source rows are added in Week 8 once the
-- OpenAI-compatible adapter exists. Pricing in USD per million tokens.
insert into models (id, provider, model_id, display_name, tier,
                    cost_in_per_mtok, cost_out_per_mtok, context_window,
                    supports_tools, supports_streaming)
values
    ('anthropic/claude-opus-5',   'anthropic', 'claude-opus-5',   'Claude Opus 5',   'frontier', 5.00, 25.00, 1000000, true, true),
    ('anthropic/claude-sonnet-5', 'anthropic', 'claude-sonnet-5', 'Claude Sonnet 5', 'balanced', 3.00, 15.00, 1000000, true, true),
    ('anthropic/claude-haiku-4-5','anthropic', 'claude-haiku-4-5','Claude Haiku 4.5','budget',   1.00,  5.00,  200000, true, true);

-- ============================================================ usage + cost
--
-- Per-request cost attribution. Cache reads are tracked separately because they
-- bill at ~0.1x — folding them into input_tokens would overstate spend by ~10x
-- on the contextual-retrieval path.

create table llm_usage (
    id                bigserial   primary key,
    owner_id          uuid,
    request_id        text,
    model_id          text        not null references models (id),
    task              text        not null,  -- synthesis | classify | contextualize | judge | agent
    input_tokens      int         not null default 0,
    output_tokens     int         not null default 0,
    cache_read_tokens int         not null default 0,
    cache_write_tokens int        not null default 0,
    cost_usd          numeric(12, 6),
    latency_ms        int,
    ttft_ms           int,
    created_at        timestamptz not null default now()
);

create index llm_usage_owner_time_idx on llm_usage (owner_id, created_at desc);

-- BRIN rather than B-tree: this table is append-only and physically ordered by
-- time, which is exactly the access pattern BRIN is built for — at a fraction of
-- the index size. This is also why TimescaleDB is not here (docs/ARCHITECTURE.md).
create index llm_usage_time_brin_idx on llm_usage using brin (created_at);

-- ============================================================ user settings

create table user_settings (
    owner_id             uuid primary key,
    default_model_id     text references models (id),
    monthly_budget_usd   numeric(10, 2),
    created_at           timestamptz not null default now(),
    updated_at           timestamptz not null default now()
);

-- ============================================================ event publication
--
-- Spring Modulith's JDBC event publication registry — the durable outbox described
-- in docs/ARCHITECTURE.md. Modulith can create this table itself, but that initializer and
-- Flyway both run at startup with no ordering between them: whichever creates a
-- table first leaves the schema non-empty for the other. Owning the DDL here makes
-- the migration the single source of truth, so `modulith.events.jdbc
-- .schema-initialization.enabled` is set to false.
--
-- This is the v2 schema shipped with Spring Modulith 2.1.0
-- (org/springframework/modulith/events/jdbc/schemas/v2/schema-postgresql.sql).
-- A Modulith upgrade that changes the schema version needs a matching migration.

create table event_publication (
    id                     uuid        not null primary key,
    listener_id            text        not null,
    event_type             text        not null,
    serialized_event       text        not null,
    publication_date       timestamptz not null,
    completion_date        timestamptz,
    status                 text,
    completion_attempts    int,
    last_resubmission_date timestamptz
);

-- Resubmission looks events up by payload, and the hash index is roughly half the
-- size of a B-tree for equality-only lookups on text this wide.
create index event_publication_serialized_event_hash_idx
    on event_publication using hash (serialized_event);

-- Incomplete publications are the ones the registry replays on restart.
create index event_publication_by_completion_date_idx
    on event_publication (completion_date);
