import type { NextConfig } from "next";

const config: NextConfig = {
  // `next dev` otherwise writes web/AGENTS.md and web/CLAUDE.md on every start, and both
  // arrive untracked in a tree that was clean before the documented dev command was run.
  // Their content is generated by the installed Next version, so committing them makes an
  // unrelated diff appear in somebody's branch the next time that version changes. The
  // reference for this Next version ships in node_modules/next/dist/docs/.
  agentRules: false,

  // Emits a self-contained server bundle with only the dependencies actually reached,
  // which is what lets the container image carry the build output instead of the whole
  // node_modules tree.
  output: "standalone",

  // The Spring service owns the API contract; the frontend proxies to it rather
  // than reimplementing routes under app/api. See README.md.
  // Everything the browser talks to is proxied, not just the data API. Sign-in puts a
  // session cookie on the authorization server and the interface later re-authorizes
  // against it silently; a cookie set on a different origin would be a third-party cookie,
  // which browsers increasingly do not send. One origin makes that a non-question.
  async rewrites() {
    const api = process.env.API_BASE_URL ?? "http://localhost:8080";
    return [
      { source: "/api/:path*", destination: `${api}/api/:path*` },
      { source: "/oauth2/:path*", destination: `${api}/oauth2/:path*` },
      // Registration, verification and reset. Distinct from /auth/callback below, which
      // is a page of this application and is deliberately not proxied.
      { source: "/auth/register", destination: `${api}/auth/register` },
      { source: "/auth/verify", destination: `${api}/auth/verify` },
      { source: "/auth/reset", destination: `${api}/auth/reset` },
      { source: "/auth/reset-request", destination: `${api}/auth/reset-request` },
      { source: "/login", destination: `${api}/login` },
      { source: "/logout", destination: `${api}/logout` },
      { source: "/.well-known/:path*", destination: `${api}/.well-known/:path*` },
    ];
  },
};

export default config;
